### ISSUE TITLE
Are you going to translate kageboushis epiloge too?

### ISSUE THREAD

**Issue by yagamisempai** [07th-mod/higurashi-console-arcs#16]
https://www.youtube.com/watch?v=MnUteKafdUI&t=29s

**Comment by DoctorDiablo** [comment]
Yeah, I'd like to translate all these little extra bits of content.

Most chapters have a prologue and an epilogue and you kind of have to read them in order for them to make sense, so we'd have to go back and do all of them.  Some work was done on the Onikakushi prologue, but that's the only one so far.

**Comment by enumag** [comment]
@DoctorDiablo Do you want to translate these for the Tsuki release or later?

**Comment by DoctorDiablo** [comment]
@enumag Probably best to come back to these later.  Translating will take a while, and we still haven't figured out a good way to add scenes like this yet.

**Comment by enumag** [comment]
@DoctorDiablo So what are the issues with these prologues / epilogues? If each chapter has one, can't we just add them to their beginning or end respectively?

**Comment by DoctorDiablo** [comment]
There are also prologues/epilogues in the main 8 arcs, and you kind of need to read those too for these to make sense.  But we decided against adding them in their respective arcs because they're overly spoilery.  So, we need to add them in the console arcs patch somewhere.

I'm also having some trouble figuring out exactly which arcs have epilogues.  The only way I can think of to locate them is to play through each arc in Sui and see when they play, which is entirely doable, but slow and tedious...

**Comment by DoctorDiablo** [comment]
Included in v5.0.0 release.

**Comment by enumag** [comment]
@DoctorDiablo Which prologues / epilogues are included in 5.0? Just Kageboushi or some others too?

**Comment by DoctorDiablo** [comment]
All of them!  There are 3 prologues and 3 epilogues total.
