### ISSUE TITLE
Tsukiotoshi Release

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/higurashi-console-arcs#18]
@07th-mod/modding-team  I just finished translating and editing Tsuki, so we're at the point where we can start integrating the console arcs with all the latest features and then package it into a proper release.  As far as I know, these are the tasks we still need to take care of.

- [x] Tsukiotoshi scripts need to be run through the compiler to add the ADV, new dll, and lipsync changes.
- [x] Some of the Someutsushi and Kageboushi scripts also need to be rerun to include a few bug fixes and features from the past month.  All of Some and Kage need to be converted to lipsync, too.
- [x] Sprites and other images need to be renamed and organized to match the folder structure used in the other arcs (sprites with _night and _sunset need to be moved to their respective folders), and then scripts need to be updated to point to the renamed files.
- [x] Existing sprites and backgrounds need to be replaced with the high resolution equivalent, instead of the 720p versions used now.
- [x] CG archive needs to include the _0, _1, and _2 versions of all sprites for lipsync to work.
- [x] Spectrum files for all the files in the voices archive need to be located and added to the archive.
- [ ] Need to assemble a CGAlt archive for the characters that have MangaGamer sprites
- [x] Perform testing on the chapter select screen and tips screens (because they're implemented in a unique way that could conflict with other changes)
- [x] Update the installer to point to all the latest archives.

@enumag you're the expert on probably half of these, but let me know what I can do to help you out.  I don't want to dump a million things on you.

Here are the latest archives with all the files needed to play the patch.  I'll upload these to GitHub after all the above changes are sorted out.
[ConsoleArcs-CG](http://www.mediafire.com/file/o5mtcq41lnhkd2s/ConsoleArcs-CG.zip)
[ConsoleArcs-BGM](http://www.mediafire.com/file/8aqchdryactuesp/ConsoleArcs-BGM.zip)
[ConsoleArcs-voice](http://www.mediafire.com/file/7k2bp1l1116cbss/ConsoleArcs-voice.zip)
[ConsoleArcs-SE](http://www.mediafire.com/file/avm0jyf5va3hq3j/ConsoleArcs-SE.zip)

**Comment by enumag** [comment]
The thing is that even I need to figure out how to make these changes first because the console arcs are a bit different from the main arcs. So you can't really help me. The priority here is for me to write it all down so that we can re-use the approach when you're done with the next chapter and so that my assistance is not required. Not that I mind doing it, it's just bad to rely on one specific person no matter who it is.

I'll need to ask some questions and might need idealpersona to make some tweaks. I'll catch you guys on Discord later.

**Comment by ItaloKnox** [comment]
Congrats on finishing it! Just is coming just at the right time, because a few days ago I asked @VocalNight to include the console arcs in the new installer. [Here is the repo for the installer](https://github.com/07th-mod/Higurashi_Installer_WPF), in case you want to check it out.

I'll handle the installer updates, I just need you to add the files to ***Hanyuu***. You can leave the old builds in Nipah, I'll archive them later. Ping me when you do it and I'll update the installer. That new installer I linked above is already working with the current stable version, so you might also want to update your documentation to link to the latest version of it.

I have around 5gb of server space left at this moment so we need to be a little careful. It's either Meakashi or Tsukiotoshi, one at a time. Either way, the server is ready in case you guys need me to recompile. 👍

**Comment by DoctorDiablo** [comment]
I did this arc manually.  I got the porting work done before the script work was completed.

Looking forward to using it on the next arc!  It should automate a lot of the process.

**Comment by irlPM** [comment]
Holy shit, you did this process 3 times manually, I can't thank you enough for this work. Thank you so much for letting me and a lot of other peoples enjoy the console arcs.

**Comment by enumag** [comment]
@DoctorDiablo The compiler for new graphics patch is done, I'll let Italo compile it later. Here are all the files the compiler was unable to locate, those need to be add manually. I've change paths for the scenario images by the way. There are some BGM things mixed in too. I can find some of these myself but considering there are a lot ot text images for tsuki that need translation I'll leave this up to you while I move onto compiling voice + spectrum pack.

```
File CG/scenario_select.png not found.
File CG/scenario/someutsushi_a.png not found.
File CG/scenario/someutsushi_a_j.png not found. // Ignore
File CG/scenario/someutsushi_b.png not found.
File CG/scenario/someutsushi_b_j.png not found.
File CG/scenario/someutsushi_c.png not found.
File CG/scenario/someutsushi_c_j.png not found.
File CG/scenario/kageboushi_a.png not found.
File CG/scenario/kageboushi_a_j.png not found. // Ignore
File CG/scenario/kageboushi_b.png not found.
File CG/scenario/kageboushi_b_j.png not found.
File CG/scenario/kageboushi_c.png not found.
File CG/scenario/kageboushi_c_j.png not found.
File CG/scenario/tsukiotoshi_a.png not found.
File CG/scenario/tsukiotoshi_a_j.png not found. // Ignore
File CG/scenario/tsukiotoshi_b.png not found.
File CG/scenario/tsukiotoshi_b_j.png not found.
File CG/scenario/tsukiotoshi_c.png not found.
File CG/scenario/tsukiotoshi_c_j.png not found.
File CG/bg_216.png not found.
File CG/end05_kag.png not found.
File CG/text/monologue_some1.png not found.
File CG/text/monologue_some1_j.png not found.
File CG/text/monologue_some2.png not found.
File CG/text/monologue_some2_j.png not found.
File CG/text/title_some.png not found.
File CG/text/title_some_j.png not found.
File CG/text/monologue_some3.png not found.
File CG/text/monologue_some3_j.png not found.
File CG/end02_som.png not found.
File CG/text/monologue_tsuki1.png not found.
File CG/text/monologue_tsuki1_j.png not found.
File CG/text/monologue_tsuki2.png not found.
File CG/text/monologue_tsuki2_j.png not found.
File CG/text/title_tsuki.png not found.
File CG/text/title_tsuki_j.png not found.
File CG/text/monologue_tsuki3.png not found.
File CG/text/monologue_tsuki3_j.png not found.
File CG/text/tuki_fre.png not found.
File CG/text/tuki_fre_j.png not found.
File CG/text/tuki_waratte1.png not found.
File CG/text/tuki_waratte1_j.png not found.
File CG/text/tuki_waratte2.png not found.
File CG/text/tuki_waratte2_j.png not found.
File CG/text/tuki_waratte4.png not found.
File CG/text/tuki_waratte4_j.png not found.
File BGM/anahori.ogg not found.
File CG/text/tuki_hitogoroshi1.png not found.
File CG/text/tuki_hitogoroshi1_j.png not found.
File CG/text/tuki_hitogoroshi2.png not found.
File CG/text/tuki_hitogoroshi2_j.png not found.
File CG/text/tuki_hitogoroshi3.png not found.
File CG/text/tuki_hitogoroshi3_j.png not found.
File CG/text/tuki_hitogoroshi4.png not found.
File CG/text/tuki_hitogoroshi4_j.png not found.
File BGM/loop131.ogg not found.
File CG/text/oni_gomen1.png not found.
File CG/text/oni_gomen1_j.png not found.
File CG/text/oni_gomen2.png not found.
File CG/text/oni_gomen2_j.png not found.
File CG/text/oni_gomen3.png not found.
File CG/text/oni_gomen3_j.png not found.
File BGM/kawa.ogg not found.
File CG/text/tuki_rena1.png not found.
File CG/text/tuki_rena1_j.png not found.
File CG/text/tuki_rena2.png not found.
File CG/text/tuki_rena2_j.png not found.
File CG/text/tuki_rena3.png not found.
File CG/text/tuki_rena3_j.png not found.
File CG/text/tuki_rena4.png not found.
File CG/text/tuki_rena4_j.png not found.
File CG/text/tuki_rena5.png not found.
File CG/text/tuki_rena5_j.png not found.
File CG/logoblack.png not found.
```

**Comment by enumag** [comment]
I've updated the scripts with ADV/DLL/LipSync changes and created some issues for Italo and jwgrlrrajn. I think that's it for my part. Let me know if you think I forgot anything or need my assistance with something else.

Documentation is a bit problematic. The main part of my work was to prepare the scripts needed for compilation. For the next chapter it's pretty much down to running just one [command](https://github.com/07th-mod/higurashi-patch-compiler/blob/master/src/Command/ConsoleArcUpgrade.php). The problem is that it might not work right away because the current script also changes the directory structure which should not be needed anymore. I guess I'll have to finish the work when Taraimawashi is translated.

**Comment by enumag** [comment]
@DoctorDiablo Am I supposed to delete the vanilla BGM directory before applying the patch or not?

**Comment by enumag** [comment]
The pre-release is missing 2 BGMs:

```
BGM/anahori.ogg
BGM/kawa.ogg
```

**Comment by DoctorDiablo** [comment]
Just added those two missing BGMs to the archive.  If you don't want to re-download the whole thing, they're both also in the SE folder.

**Comment by DoctorDiablo** [comment]
Marking this closed now that there's a full release.  The only outstanding item is the MG sprites, and we have a separate issue for those.
