### ISSUE TITLE
Pink font

### ISSUE THREAD

**Issue by joaovictorsena** [07th-mod/higurashi-console-arcs#574]
Hello, my game has a weird pink font, but it works on the vanilla version.

![Screenshot_1](https://user-images.githubusercontent.com/45524271/130137546-71490291-e631-446e-8b48-77ac2c0b988b.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/45524271/130137577-cb558a2a-983f-4e76-b401-6b76827b9f0d.jpg)

[output_log.txt](https://github.com/07th-mod/higurashi-console-arcs/files/7017477/output_log.txt)

**Comment by DoctorDiablo** [comment]
Looks like something went wrong with the sharedassets0.assets file. Are you playing on Windows? Maybe you got the wrong version of it somehow.  If you look in the HigurashiEp04_Data folder, try replacing it with the version that's called sharedassets0.assets.backup. That's the original version of the file. (That'll cause other issues but it should tells us if that's where the problem came from.)

**Comment by joaovictorsena** [comment]
Yes, I'm playing on Windows. I did what you told me, but it still doesn't work.

**Comment by DoctorDiablo** [comment]
Try redownloading the [UI files](https://07th-mod.com/ui.php?chapter=himatsubushi&os=win&unity=5.4.1f1) and dropping those in place. That may fix it.

**Comment by joaovictorsena** [comment]
Thank you, now it's working.
