### ISSUE TITLE
What is Console Arcs?

### ISSUE THREAD

**Issue by K14Mua** [07th-mod/higurashi-console-arcs#599]
I bought all the cicada games on Steam

- Higurashi When They Cry Hou - Ch.1 Onikakushi
- Higurashi When They Cry Hou - Ch.2 Watanagashi
- Higurashi When They Cry Hou - Ch.3 Tatarigoroshi
- Higurashi When They Cry Hou - Ch.4 Himatsubushi
- Higurashi When They Cry Hou - Ch. 5 Meakashi
- Higurashi When They Cry Hou - Ch.6 Tsumihoroboshi
- Higurashi When They Cry Hou - Ch.7 Minagoroshi
- Higurashi When They Cry Hou - Ch.8 Matsuribayashi
- Higurashi When They Cry Hou - Rei
- Higurashi When They Cry Hou+

Now I'm reading chapter 8, putting the puzzle together. But what does Console Arcs mean? Is this some kind of separate game that is not on Steam? Can I buy it somewhere and what is it?

**Comment by drojf** [comment]
> Now I'm reading chapter 8, putting the puzzle together. But what does Console Arcs mean? Is this some kind of separate game that is not on Steam? Can I buy it somewhere and what is it?

To play the console arcs, you only need "Higurashi When They Cry Hou - Ch.4 Himatsubushi" installed. Our mod installer will then overwrite that chapter with the Console Arcs. You don't need to buy it as a separate game to play it. 

However, because both our normal "mod" for ch4 and the console arcs install to the same chapter, you can only have one installed at a time (unless you make a copy of the game folder). So I would recommend you at least play through chapter 4 before you try to install the console arcs, to keep things simple.

> But what does Console Arcs mean? 

We have a short description on our wiki about the console arcs

https://07th-mod.com/wiki/Higurashi/Higurashi-Getting-started/#console-arcs-extra-chapters

**Comment by drojf** [comment]
> GitHub issues are not for support. Please direct these type of questions to our Discord.

Because we don't get Github support queries like this often, I don't mind answering them on Github, even if they might be better answered over discord, or are in the wrong repo (I just transfer them to the right repo).
