### ISSUE TITLE
Not sure what I'm doing wrong with the installation?

### ISSUE THREAD

**Issue by Yoyoenix91** [07th-mod/higurashi-console-arcs#9]
Firstly, thank you for all your hard work and effort! I'm truly excited to read Someutsushi. Sadly, however, I'm not getting it to work properly. 

I have Himatsubushi installed from Steam, and from there I copy the entire Himatsubushi installation folder to my desktop. From there, I delete the appropriate folders in the streaming assets and copy over from 1.4. Once I run the novel, it's still Himatsubushi, complete with text and CGs. 

I tried just literally installing it over the default directory I have set up with Steam (even though you advised against it, I don't have it in my normal Program Files, to begin with), and it DID import the text... but everything else was black. 

I'm not exactly sure what I'm doing wrong here, sadly. :- <

**Comment by ItaloKnox** [comment]
Did you remember to delete the files inside the ``CompiledUpdateScripts`` directory?

**Comment by ItaloKnox** [comment]
Oh, by the way, when you copy the folder and run the game in that edited folder, the game **will** call the Steam version instead of the copy. That happens every time (and we did a little change to prevent that, but not on the console arcs yet), and that's why you have the original game running despite deleting everything because it runs from the original folder. This shouldn't happen in the drm-free version, though.

In this case, I suggest doing what I said above in the default installation directory. You won't have Hima anymore but the game should work. Reinstall the game, patch and clean the ``CompiledUpdateScripts`` folder.

**Comment by Yoyoenix91** [comment]
Oh, well that explains a lot! I thought I was going crazy for a while. lol

Is there a way to have both Himatsubushi and Someutsushi installed at the same time? If not, I can just work around that.

**Comment by DoctorDiablo** [comment]
Check to make sure you have the graphics option set to updated graphics.  It'll get confused if you have it set to original because in this case there are only PS3 sprites.

Right now it's a little difficult to have Hima and console arcs installed at the same time.  But you can rename your regular Hima install folder to Himatsubushi.original and then set up the console arcs in the Himatsubushi folder.  When you want to read Hima again you can rename it back.  Sorry, it's kind of a hassle at the moment.  Hoping to streamline it in the future.

**Comment by Yoyoenix91** [comment]
Thanks for that little tidbit! That's what I'll do, and I hope it helps others until things get updated. 

One last thing: I did what you said, and it finally showed me the portrait for Fujita, but the background CGs were still black. Additionally, I saw Fujita suddenly look very... fat. It was as though he went from stretched 4:3 to 16:9. Not sure if that was a side effect of my PC, or how fullscreen works, or what have you, but it was very amusing. Nonetheless, the CGs still aren't showing for me. I'll try reinstalling again and see how it goes.

**Comment by DoctorDiablo** [comment]
Sounds like the install didn't complete successfully.  The base game is in 4:3 and the patch converts it to 16:9, so some of that config must be missing.

Can you post a screenshot of your StreamingAssets folder?

**Comment by Yoyoenix91** [comment]
The strangest thing happened. I swear I didn't touch anything, and now everything just... works. Portraits, CGs, voices, everything. 

![image](https://user-images.githubusercontent.com/34481705/34084775-10ef34a0-e354-11e7-8a5b-377def1e4fc9.png)

Here is a screenshot of my folder, just in case you need it.

![image](https://user-images.githubusercontent.com/34481705/34084776-25d883f8-e354-11e7-897d-583b0267acdb.png)

I'm just glad it's working now! I can read this before Himatsubushi, so I won't need to have both installed at once. :- 3

**Comment by DoctorDiablo** [comment]
Weird, no idea what's going on there.  Maybe it recompiled the scripts when you opened it this time and that straightened everything out?  Either way, I'm glad you got it working.

I'm gonna mark this issue closed, but feel free to reopen it if you run into other problems.
